# Generated by Django 3.1.1 on 2020-09-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Two', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idcard',
            name='id_person',
        ),
        migrations.AddField(
            model_name='idcard',
            name='id_person',
            field=models.ManyToManyField(to='Two.Person'),
        ),
    ]
