# Generated by Django 3.1.1 on 2020-09-21 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Two', '0002_auto_20200921_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='dog',
            fields=[
                ('animal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Two.animal')),
                ('d_name', models.CharField(max_length=20)),
            ],
            bases=('Two.animal',),
        ),
    ]
