# Generated by Django 3.1 on 2020-09-19 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Two', '0004_auto_20200919_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcard',
            name='id_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Two.person'),
        ),
    ]
