# Generated by Django 3.1.1 on 2020-09-23 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Two', '0006_testupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testupload',
            name='t_img',
            field=models.ImageField(upload_to='%Y'),
        ),
    ]
