# Generated by Django 3.1.1 on 2020-09-18 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='s_gender',
            field=models.SmallIntegerField(default=0, verbose_name=((0, 'female'), (1, 'male'))),
        ),
    ]
