# Generated by Django 3.1.1 on 2020-09-11 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Qustion',
            new_name='Question',
        ),
    ]
