# Generated by Django 3.1 on 2020-09-08 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deltest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=10)),
                ('d_cost', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
