# Generated by Django 3.1 on 2020-09-07 13:21

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('pub_date', models.DateField(default='1990-01-01')),
                ('commentcount', models.IntegerField(default=0)),
                ('readcount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=10)),
                ('c_sex', models.SmallIntegerField(verbose_name=((0, '女'), (1, '男')))),
                ('c_cost', models.FloatField(default=10.0)),
            ],
        ),
        migrations.CreateModel(
            name='PeopleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('gender', models.BooleanField()),
                ('book', models.ForeignKey(on_delete=book.models.BookInfo, to='book.bookinfo')),
            ],
        ),
    ]
